#!/usr/bin/env python

from gradelib import *

r = Runner(save("jos.out"),
           stop_breakpoint("readline"))

@test(10)
def test_divzero():
    r.user_test("divzero")
    r.match('Incoming TRAP frame at 0xefffff..',
            'TRAP frame at 0xf.......',
            '  trap 0x00000000 Divide error',
            '  eip  0x008.....',
            '  ss   0x----0023',
            '.00001000. free env 00001000',
            no=['1/0 is ........!'])

@test(10)
def test_softint():
    r.user_test("softint")
    r.match('Welcome to the JOS kernel monitor!',
            'Incoming TRAP frame at 0xefffffbc',
            'TRAP frame at 0xf.......',
            '  trap 0x0000000d General Protection',
            '  eip  0x008.....',
            '  ss   0x----0023',
            '.00001000. free env 0000100')

@test(10)
def test_badsegment():
    r.user_test("badsegment")
    r.match('Incoming TRAP frame at 0xefffffbc',
            'TRAP frame at 0xf.......',
            '  trap 0x0000000d General Protection',
            '  err  0x00000028',
            '  eip  0x008.....',
            '  ss   0x----0023',
            '.00001000. free env 0000100')

run_tests()
