#!/usr/bin/env python

import re
from gradelib import *

r = Runner(save("jos.out"),
           stop_breakpoint("readline"))

def E(s, trim=False):
    """Expand $En in s to the environment ID of the n'th user
    environment."""

    tmpl = "%x" if trim else "%08x"
    return re.sub(r"\$E([0-9]+)",
                  lambda m: tmpl % (0x1000 + int(m.group(1))-1), s)

@test(5)
def test_dumbfork():
    r.user_test("dumbfork")
    r.match(E(".00000000. new env $E1"),
            E(".$E1. new env $E2"),
            "0: I am the parent.",
            "9: I am the parent.",
            "0: I am the child.",
            "9: I am the child.",
            "19: I am the child.",
            E(".$E1. exiting gracefully"),
            E(".$E1. free env $E1"),
            E(".$E2. exiting gracefully"),
            E(".$E2. free env $E2"))


run_tests()
